name: usecase
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+5
  port:
    path: ../port
dev_dependencies:
  test: ^0.12.0