name: step01
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+5
  angular_components: ^0.9.0-alpha+4
  angular_forms: 1.0.1-alpha+5
  browser: ^0.10.0
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  build_runner: ^0.7.8
  build_web_compilers: ^0.2.1
  sass_builder: ^1.1.2
web:
  compiler:
    debug: dartdevc
