analyzer:
  strong-mode: true
  plugins:
    angular:
      enabled: true
  errors:
    unused_element: warning
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    uri_has_not_been_generated: ignore

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
